schema {
  query: Query
  mutation: Mutation
}

type Query {
  sources: [Source!]!
  source(id: ID!): Source!
  photos(first: Int, cursor: String): PhotoConnection!
  photosErrors(first: Int, cursor: String): PhotoErrorConnection!
  syncStatus(workflowId: ID!): SyncStatus
}

input CreateS3SourceInput {
  name: String!
  s3_endpoint: String!
  s3_region: String!
  s3_bucket: String!
  s3_api_key: String!
  s3_api_key_secret: String!
}

input UpdateS3SourceInput {
  id: ID!
  name: String
  s3_endpoint: String
  s3_region: String
  s3_bucket: String
  s3_api_key: String
  s3_api_key_secret: String
}

input DeleteS3SourceInput {
  id: ID!
}

input SyncSourceInput {
  id: ID!
}

type Mutation {
  createS3Source(input: CreateS3SourceInput!): S3Source!
  updateS3Source(input: UpdateS3SourceInput!): S3Source!
  deleteS3Source(input: DeleteS3SourceInput!): S3Source!
  syncSource(input: SyncSourceInput!): String!
}

interface Source {
  id: ID!
  name: String!
  sync_workflow_id: String
}

type S3Source implements Source {
  id: ID!
  name: String!
  sync_workflow_id: String
  s3_endpoint: String!
  s3_region: String!
  s3_bucket: String!
  s3_api_key: String!
  s3_api_key_secret: String!
}

type PageInfo {
  hasNextPage: Boolean
  endCursor: String
}
type Photo {
  id: ID!
  token: String!
  date_created: Int!
  width: Int!
  height: Int!
  lat: Float
  lng: Float
}
type PhotoEdge {
  cursor: String!
  node: Photo!
}
type PhotoConnection {
  edges: [PhotoEdge!]!
  pageInfo: PageInfo!
  errorCount: Int!
}

type PhotoError {
  id: ID!
  objectKey: String!
  error: String!
}
type PhotoErrorEdge {
  cursor: String!
  node: PhotoError!
}
type PhotoErrorConnection {
  edges: [PhotoErrorEdge!]!
  pageInfo: PageInfo!
}

enum SyncStatusState {
  queued
  running
  paused
  errored
  terminated
  complete
  waiting
  waitingForPause
  unknown
}

type SyncStatus {
  status: SyncStatusState!
  error: String
}
